// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxzbnjhuksvkigwtybwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4emJuamh1a3N2a2lnd3R5YndrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzM0MTgsImV4cCI6MjA2NTkwOTQxOH0.wRKKLJbyWYAq0uDyJ4xzrd94iHi6b7dLJ-Pt_KuTrMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});